PLATFORM_CORE_REPO=https://mygit.th-deg.de/thd-spatial-ai/microservices/platform-core.git
LIBS_REPO=https://mygit.th-deg.de/thd-spatial-ai/microservices/react-shared-components.git
INFRASTRUCTURE_REPO=https://mygit.th-deg.de/thd-spatial-ai/microservices/backend-infrastructure.git
WEBSERVICE_REPO=https://mygit.th-deg.de/tcf_s6et/docker_webservice.git
WEBSERVICE_BRANCH=pylovo
PYLOVO_REPO=https://mygit.th-deg.de/thd-spatial-ai/data_pipelines/pylovo.git
