SIMENGINE_REPO=https://github.com/enerplanet/simulation-engine.git
PYLOVO_REPO=https://github.com/enerplanet/enerplanet-pylovo.git
OPENTECHDB_REPO=https://github.com/THD-Spatial-AI/OpenTech-DB.git
OPENTECHDB_DIR=OpenTech-DB
