// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/models": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Returns a paginated list of energy planning models the user has access to,\nfiltered by workspace and search query. Includes shared and workspace-scoped models.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EnerPlanET"
                ],
                "summary": "List models for the authenticated user",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Max results per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search models by title (case-insensitive)",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by workspace ID",
                        "name": "workspace_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.GetModelsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/city2tabula/enrich": {
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Given a drawn area (country, its PyLovo osm_ids, and the bbox) returns a per-osm_id\nmerge map of BuEM envelope data. Returns 200 \"completed\" when every osm_id is already\nlinked, or 202 \"running\" with a run_id when a bbox-scoped pipeline run was triggered\n(the buildings resolved so far are returned alongside). Poll GET .../enrich/{run_id}.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "City2TABULA"
                ],
                "summary": "Resolve City2TABULA 3D data for a drawn area",
                "parameters": [
                    {
                        "description": "Drawn area",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.EnrichRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.EnrichResponse"
                        }
                    },
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.EnrichResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/city2tabula/enrich/{run_id}": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Proxies the City2TABULA run status. When the run has completed and country and\nosm_ids are given as query parameters, also returns the merge map for those buildings,\nso the client polls one endpoint and gets data when ready.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "City2TABULA"
                ],
                "summary": "Poll a City2TABULA enrich run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run id from the 202 enrich response",
                        "name": "run_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Country, required to receive data on completion",
                        "name": "country",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated osm_ids, required to receive data on completion",
                        "name": "osm_ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.EnrichResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No run with this id (stale or mistyped)",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/heat-demand/resolve": {
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Given a building's usage class, floor area, and (for a residential building)\nits TABULA type / construction year / country, returns its annual space-heating\ndemand (kWh/a), the specific demand (kWh/m2.a) and a source flag (\"ignis\" when a\nTABULA archetype matched, \"estimate\" otherwise). tabula_variant_code is set only\nfor source \"ignis\". hourly_profile is currently always null (source \"buem\" is not\nyet wired). A residential building that falls back to the estimate carries a\nwarning naming why.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "HeatDemand"
                ],
                "summary": "Resolve a building's annual space-heating demand",
                "parameters": [
                    {
                        "description": "Building inputs",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.HeatDemandResolveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.HeatDemandResolveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v2/pylovo/boundary": {
            "get": {
                "description": "Returns the administrative boundary polygon (GeoJSON) for a given lat/lon.\nThis is a public endpoint — no authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "EnerPlanET"
                ],
                "summary": "Get administrative boundary by coordinates",
                "parameters": [
                    {
                        "type": "number",
                        "example": 48.137,
                        "description": "Latitude",
                        "name": "lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "example": 11.575,
                        "description": "Longitude",
                        "name": "lon",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 4,
                        "description": "OSM admin level (default 4)",
                        "name": "admin_level",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.GetBoundaryResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "spatialhub_backend_internal_api_contracts.BoundaryData": {
            "type": "object",
            "properties": {
                "boundary": {
                    "description": "GeoJSON Feature"
                },
                "message": {
                    "type": "string",
                    "example": ""
                },
                "region": {
                    "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.BoundaryRegion"
                },
                "status": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.BoundaryRegion": {
            "type": "object",
            "properties": {
                "admin_level": {
                    "type": "integer",
                    "example": 4
                },
                "country": {
                    "type": "string",
                    "example": "Germany"
                },
                "country_code": {
                    "type": "string",
                    "example": "DE"
                },
                "name": {
                    "type": "string",
                    "example": "Bayern"
                },
                "osm_id": {
                    "type": "integer",
                    "example": 2145268
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.BuemBuilding": {
            "type": "object",
            "properties": {
                "envelope": {
                    "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.BuemEnvelope"
                },
                "footprint_area": {
                    "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.EnrichQuantity"
                },
                "h_room": {
                    "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.EnrichQuantity"
                },
                "n_storeys": {
                    "type": "integer",
                    "example": 3
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.BuemEnvelope": {
            "type": "object",
            "properties": {
                "elements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/spatialhub_backend_internal_city2tabula.EnvelopeElement"
                    }
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.BuemNode": {
            "type": "object",
            "properties": {
                "building": {
                    "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.BuemBuilding"
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.EnrichBbox": {
            "type": "object",
            "properties": {
                "xmax": {
                    "type": "number",
                    "example": 6.13
                },
                "xmin": {
                    "type": "number",
                    "example": 6.09
                },
                "ymax": {
                    "type": "number",
                    "example": 51.93
                },
                "ymin": {
                    "type": "number",
                    "example": 51.9
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.EnrichQuantity": {
            "type": "object",
            "properties": {
                "unit": {
                    "type": "string",
                    "example": "m"
                },
                "value": {
                    "type": "number",
                    "example": 2.5
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.EnrichRequest": {
            "type": "object",
            "properties": {
                "bbox": {
                    "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.EnrichBbox"
                },
                "country": {
                    "type": "string",
                    "example": "germany"
                },
                "osm_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "240054621",
                        "240054622"
                    ]
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.EnrichResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.EnrichedBuilding"
                    }
                },
                "missing": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "240054999"
                    ]
                },
                "resolved": {
                    "type": "integer",
                    "example": 40
                },
                "run_id": {
                    "type": "string",
                    "example": "a1b2c3d4"
                },
                "status": {
                    "type": "string",
                    "example": "completed"
                },
                "total": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.EnrichedBuilding": {
            "type": "object",
            "properties": {
                "buem": {
                    "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.BuemNode"
                },
                "match_type": {
                    "type": "integer",
                    "example": 1
                },
                "object_id": {
                    "type": "string",
                    "example": "DEBW_1"
                },
                "tabula_variant_code": {
                    "type": "string",
                    "example": "DE.N.SFH.05.Gen.ReEx.001.001"
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Unauthorized"
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.GetBoundaryResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.BoundaryData"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.GetModelsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.ModelSummary"
                    }
                },
                "limit": {
                    "type": "integer",
                    "example": 100
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "server_time": {
                    "type": "string",
                    "example": "2025-06-15T10:30:00Z"
                },
                "success": {
                    "type": "boolean",
                    "example": true
                },
                "total": {
                    "type": "integer",
                    "example": 25
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.HeatDemandHourlyProfile": {
            "type": "object",
            "properties": {
                "resolution_minutes": {
                    "type": "integer"
                },
                "start": {
                    "type": "string"
                },
                "summary": {
                    "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.HeatDemandProfileSummary"
                },
                "timeseries_ref": {
                    "type": "string"
                },
                "vectors": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.HeatDemandInputsEcho": {
            "type": "object",
            "properties": {
                "building_type": {
                    "type": "string"
                },
                "construction_year": {
                    "type": "integer"
                },
                "country": {
                    "type": "string"
                },
                "f_class": {
                    "type": "string"
                },
                "floor_area_m2": {
                    "type": "number"
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.HeatDemandProfileSummary": {
            "type": "object",
            "properties": {
                "cooling_total_kwh": {
                    "type": "number"
                },
                "electricity_total_kwh": {
                    "type": "number"
                },
                "heating_total_kwh": {
                    "type": "number"
                },
                "peak_cooling_kw": {
                    "type": "number"
                },
                "peak_heating_kw": {
                    "type": "number"
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.HeatDemandResolveRequest": {
            "type": "object",
            "properties": {
                "building_type": {
                    "type": "string",
                    "example": "SFH"
                },
                "construction_year": {
                    "type": "integer",
                    "example": 1975
                },
                "country": {
                    "type": "string",
                    "example": "germany"
                },
                "f_class": {
                    "type": "string",
                    "example": "detached"
                },
                "floor_area_m2": {
                    "type": "number",
                    "example": 120
                },
                "osm_id": {
                    "type": "string",
                    "example": "240054621"
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.HeatDemandResolveResponse": {
            "type": "object",
            "properties": {
                "heating_demand_kwh_a": {
                    "type": "integer",
                    "example": 12000
                },
                "hourly_profile": {
                    "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.HeatDemandHourlyProfile"
                },
                "inputs_echoed": {
                    "$ref": "#/definitions/spatialhub_backend_internal_api_contracts.HeatDemandInputsEcho"
                },
                "osm_id": {
                    "type": "string"
                },
                "source": {
                    "type": "string",
                    "example": "estimate"
                },
                "specific_heating_demand_kwh_m2a": {
                    "type": "number",
                    "example": 100
                },
                "tabula_variant_code": {
                    "type": "string"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "spatialhub_backend_internal_api_contracts.ModelSummary": {
            "type": "object",
            "properties": {
                "country": {
                    "type": "string",
                    "example": "DE"
                },
                "created_at": {
                    "type": "string",
                    "example": "2025-06-15T10:30:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Heating model for Munich south"
                },
                "from_date": {
                    "type": "string",
                    "example": "2025-01-01T00:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 42
                },
                "is_active": {
                    "type": "boolean",
                    "example": false
                },
                "is_copy": {
                    "type": "boolean",
                    "example": false
                },
                "region": {
                    "type": "string",
                    "example": "Bavaria"
                },
                "resolution": {
                    "type": "integer",
                    "example": 8
                },
                "status": {
                    "type": "string",
                    "example": "draft"
                },
                "title": {
                    "type": "string",
                    "example": "Munich District Heating"
                },
                "to_date": {
                    "type": "string",
                    "example": "2025-12-31T00:00:00Z"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2025-06-15T10:30:00Z"
                },
                "user_email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "user_id": {
                    "type": "string",
                    "example": "f47ac10b-58cc-4372-a567-0e02b2c3d479"
                },
                "workspace_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "spatialhub_backend_internal_city2tabula.EnvelopeElement": {
            "type": "object",
            "properties": {
                "area": {
                    "$ref": "#/definitions/spatialhub_backend_internal_city2tabula.Quantity"
                },
                "azimuth": {
                    "$ref": "#/definitions/spatialhub_backend_internal_city2tabula.Quantity"
                },
                "id": {
                    "type": "string",
                    "example": "w1"
                },
                "tilt": {
                    "$ref": "#/definitions/spatialhub_backend_internal_city2tabula.Quantity"
                },
                "type": {
                    "type": "string",
                    "example": "wall"
                }
            }
        },
        "spatialhub_backend_internal_city2tabula.Quantity": {
            "type": "object",
            "properties": {
                "unit": {
                    "type": "string",
                    "example": "m2"
                },
                "value": {
                    "type": "number",
                    "example": 30
                }
            }
        }
    },
    "securityDefinitions": {
        "APITokenAuth": {
            "description": "API token obtained via POST /api/users/{userId}/tokens. Format: Bearer whf_xxx",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "SessionAuth": {
            "description": "Session cookie obtained via POST /api/login",
            "type": "apiKey",
            "name": "session_id",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "EnerPlanET API",
	Description:      "Unified API for the EnerPlanET energy planning platform.\nIncludes native backend endpoints and proxied Pylovo (grid/boundary) services.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
